version: '3.8'

services:
  web:
    image: "ghcr.io/javedh-dev/link-tools/web:latest"
    build: ./webapp
    restart: unless-stopped
    environment:
      - API_URL=/api
    networks:
      - link-tools
  api:
    image: "ghcr.io/javedh-dev/link-tools/api:latest"
    build: ./api
    restart: unless-stopped
    volumes:
      - db:/app/db
    networks:
      - link-tools
  proxy:
    image: "ghcr.io/javedh-dev/link-tools/proxy:latest"
    build: .
    restart: unless-stopped
    networks:
      - link-tools
    ports:
      - "80:80"
networks:
  link-tools:
    driver: bridge

volumes:
  db:
